<?php if (Mage::getStoreConfig('social/general/jquery')): ?>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<?php endif;?>
    
<script type="text/javascript">
    jQuery = jQuery.noConflict();
</script>

<script src="<?php echo $this->getSkinUrl('ksv_social/js/userscripts.js') ?>" type="text/javascript"></script>

<!--[if lte IE 7]>
    <link rel="stylesheet" href="<?php echo $this->getSkinUrl('ksv_social/css/ie7.css?ver=3.2.1') ?>" type="text/css" media="screen" />
<![endif]-->

<!--[if lte IE 7]>
    <script src="<?php echo $this->getSkinUrl('ksv_social/js/userscripts-ie7.js') ?>" type="text/javascript"></script>
<![endif]-->
